### ISSUE TITLE
Setting up automatic testing

### ISSUE THREAD

**Issue by masmangan** [rcopstein/ES2-Families2Persons#5]
See ocularium project.

**Comment by ggirotto** [comment]
Found Astah example file. It can be found at https://github.com/rcopstein/ES2-Families2Persons/blob/master/ATL/ATL_EXAMPLE.asta

**Comment by ggirotto** [comment]
A test example from another project can be found at Ocularium -> https://github.com/ocularium/ocularium/blob/master/simpleocl/src/test/java/ocularium/ImportActionTest.java

**Comment by ggirotto** [comment]
Our tests can be found at the following directory https://github.com/rcopstein/ES2-Families2Persons/tree/master/AstahAtlPlugin/src/test/java/com/copstein

**Comment by ggirotto** [comment]
I've tried to execute tests by executing 'mvn test', which returned an error at pom.xml file. I had to paste

```
<properties>
				<astahPath>/Applications/astah professional/astah professional.app/Contents/Java</astahPath>
</properties>
```

at https://github.com/rcopstein/ES2-Families2Persons/blob/master/AstahAtlPlugin/pom.xml

**Comment by ggirotto** [comment]
After that, running `mvn test` worked after changes
